{{- if .Values.certificate.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "iap.fullname" . }}-tls
  labels:
    {{- include "iap.labels" . | nindent 4 }}
    app.kubernetes.io/component: "certificate"
  annotations:
    kubernetes.io/description: "Itential Automation Platform TLS certificates"
    {{- include "iap.annotations" . | nindent 4 }}
  {{- with .Values.certificate.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "iap.fullname" . }}-tls-secret
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
    {{- if hasKey (.Values.certificate.issuer) "group" }}
    group: {{ .Values.certificate.issuer.group }}
    {{- end }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  duration: {{ .Values.certificate.duration }}
  commonName: {{ .Values.certificate.commonName | quote }}
  dnsNames:
    - {{ .Values.certificate.commonName | quote -}}
    {{/* This will add DNS names for each of the pods for direct access */}}
    {{- range $i := until (.Values.replicaCount | int) }}
    - {{ printf "%s-%s-%d.%s" (include "iap.name" $) $.Release.Namespace $i $.Values.certificate.domain | quote }}
    {{- end }}
  {{- if or .Values.certificate.ipAddresses .Values.certificate.includeServiceIPs }}
  ipAddresses:
  {{- range .Values.certificate.ipAddresses }}
    - {{ . | quote }}
  {{- end }}
  {{- if .Values.certificate.includeServiceIPs }}
  {{- range .Values.certificate.services }}
    {{- if .clusterIP }}
    - {{ .clusterIP | quote }}
    {{- end }}
    {{- if .loadBalancerIP }}
    - {{ .loadBalancerIP | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- with .Values.certificate.privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificate.keystores }}
  keystores:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificate.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
