name: Helm Chart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  helm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Lint Helm chart
        run: helm lint .

      - name: Run Helm unit tests
        run: helm unittest --strict .
